[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "agensight-dev"
version = "0.5.4"
authors = [
    {name = "Pype", email = "deepesh@pypeai.com"},
]
description = "A Python SDK for logging and visualizing OpenAI agent interactions, with a built-in CLI and web dashboard."
readme = "readme.sdk.md"
license = {text = "MIT"}
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
keywords = ["openai", "ai", "agents", "logging", "visualization", "sdk", "cli", "dashboard"]
dependencies = [
    "openai>=1.0.0",
    "requests>=2.28.0",
    "flask>=2.0.0",
    "nest_asyncio>=1.5.0",
    "flask_cors>=4.0.0",
    "fastapi>=0.100.0",
    "uvicorn>=0.20.0",
    "ragas>=0.1.0",
    "sqlalchemy>=2.0.0",
    "pydantic>=2.0.0",
    "starlette>=0.27.0",
    "typing-extensions>=4.0.0",
    "python-multipart>=0.0.6",
    "werkzeug>=2.0.0",
    "jinja2>=3.0.0",
    "aiofiles>=23.0.0",
    "click>=8.0.0",
    "opentelemetry-sdk>=1.20.0",
    "opentelemetry-api>=1.20.0",
    "opentelemetry-instrumentation>=0.41b0",
    "opentelemetry-instrumentation-openai>=0.21b0",
    "anthropic>=0.25.0",
    "scikit-learn>=1.0.0",
    "pandas>=1.3.0",
    "numpy>=1.20.0",
    "google-generativeai>=0.4.0",
    "retry>=0.9.2",
    "rich>=13.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "black>=23.0.0",
    "isort>=5.12.0",
    "flake8>=6.0.0",
    "mypy>=1.0.0",
]
test = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0",
    "pytest-mock>=3.10.0",
]
optional = [
    "Dbias",
    "allennlp",
]

[project.scripts]
agensight = "cli.main:main"

[project.urls]
"Homepage" = "https://github.com/pype-ai/agensight"
"Bug Tracker" = "https://github.com/pype-ai/agensight/issues"
"Documentation" = "https://pype-db52d533.mintlify.app/introduction"
"Source Code" = "https://github.com/pype-ai/agensight"

[tool.setuptools.packages.find]
exclude = ["tests*", "docs*"]

[tool.setuptools.package-data]
agensight = [
    "_ui/build/**/*",
    "templates/**/*",
    "static/**/*",
]