name: Development Workflow

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ feature/*, bugfix/*, hotfix/* ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8 mypy bandit safety
        pip install -e .[dev]
        
    - name: Code formatting check
      run: |
        black --check --diff .
        
    - name: Import sorting check
      run: |
        isort --check-only --diff .
        
    - name: Linting
      run: |
        flake8 . --count --statistics
        
    - name: Type checking
      run: |
        mypy agensight/ --ignore-missing-imports
        
    - name: Security check
      run: |
        bandit -r agensight/ -f json -o bandit-report.json || true
        safety check --json --output safety-report.json || true
        
    - name: Upload security reports
      uses: actions/upload-artifact@v4
      with:
        name: security-reports
        path: |
          bandit-report.json
          safety-report.json

  test-ui:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: ./agensight/_ui/package-lock.json
        
    - name: Install UI dependencies
      run: |
        cd ./agensight/_ui
        npm ci
        
    - name: Run UI tests
      run: |
        cd ./agensight/_ui
        npm test -- --coverage --watchAll=false
        
    - name: Run UI linting
      run: |
        cd ./agensight/_ui
        npm run lint || true
        
    - name: Build UI
      run: |
        cd ./agensight/_ui
        npm run build

  integration-test:
    needs: [code-quality, test-ui]
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: ./agensight/_ui/package-lock.json
        
    - name: Build UI
      run: |
        cd ./agensight/_ui
        npm ci
        npm run build
        
    - name: Install Python package
      run: |
        python -m pip install --upgrade pip
        pip install -e .[test]
        
    - name: Run integration tests
      run: |
        pytest tests/integration/ -v --tb=short
        
    - name: Test CLI installation
      run: |
        agensight --help
        
    - name: Test package import
      run: |
        python -c "import agensight; print(f'Successfully imported agensight {agensight.__version__}')"